name: meta-acpfinder
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.6
  - biopython 1.78
  - filetype >= 1.0.0
  - pytest >= 3.0.0
  - pandas >= 0.15.0
  - matplotlib >= 2.1.2
  - seaborn >= 0.8.1
  - pyfaidx >= 0.5.4.1
  - pyahocorasick 1.4.0
  - pysam 0.16.0.1
  - blast 2.9.0
  - zlib
  - prodigal 2.6.3
  - pyrodigal >=2.0.0
  - diamond 0.8.36