name: macpfinder
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.6
  - biopython 1.78
  - filetype >= 1.2.0
  - progress 1.6.0
  - pytest >= 3.0.0
  - pandas >= 1.1.5
  - matplotlib >= 2.1.2
  - seaborn >= 0.8.1
  - pyfaidx >= 0.5.4.1
  - pyahocorasick 1.4.0
  - blast 2.9.0
  - prodigal >= 2.6.3
  - pyrodigal >= 2.1.0
  - diamond 0.8.36
  - fastp >=0.23.0
  - megahit 1.2.9
  - spades 3.15.5
